spring:
  datasource:
    url: jdbc:sqlserver://servercustomer.database.windows.net:1433;database=cust_db_911;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: username
    password: Password@9923
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      

server:
  port: 9091
  
  
  
  
  
  
  
  
  